// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    appId: '1:183616831570:android:a432a0f55ccaf5810c5f8b',
    messagingSenderId: '183616831570',
    projectId: 'pbl-cng',
    storageBucket: 'pbl-cng.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    appId: '1:183616831570:ios:6642da2f952ddd2a0c5f8b',
    messagingSenderId: '183616831570',
    projectId: 'pbl-cng',
    storageBucket: 'pbl-cng.firebasestorage.app',
    iosBundleId: 'com.example.pblSample',
  );

  static const FirebaseOptions web = FirebaseOptions(
    appId: '1:183616831570:web:069c915e35cd92b20c5f8b',
    messagingSenderId: '183616831570',
    projectId: 'pbl-cng',
    authDomain: 'pbl-cng.firebaseapp.com',
    storageBucket: 'pbl-cng.firebasestorage.app',
  );

}